# Generated by Django 2.1.2 on 2018-10-18 01:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0004_auto_20181017_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='user',
            field=models.ForeignKey(default=1, on_delete=models.SET(1), to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
